version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - kakarama-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_REFRESH_SECRET=your-super-secret-refresh-key-change-in-production
      - DB_TYPE=sqlite
      - SQLITE_PATH=../data/bot-kr.db
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ../data:/app/data
    networks:
      - kakarama-network
    depends_on:
      - database

  database:
    image: sqlite:latest
    volumes:
      - ../data:/data
    networks:
      - kakarama-network

networks:
  kakarama-network:
    driver: bridge

volumes:
  node_modules_frontend:
  node_modules_backend:
